/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package burgueriarafael.tela;

import burgueriarafael.basica.Cliente;
import burgueriarafael.basica.Funcionario;
import burgueriarafael.basica.Pedido;
import burgueriarafael.fachada.ClienteFachada;
import burgueriarafael.fachada.FuncionarioFachada;
import burgueriarafael.fachada.PedidoFachada;
import burgueriarafael.util.Uteis;

/**
 *
 * @author BrunoTiCaVini
 */
public class CadastrarPedido extends javax.swing.JFrame {
    
    public CadastrarPedido(){
      
    }
    public static final String TELA_MODO_EDITAR = "e";
    public static final String TELA_MODO_CADASTRAR = "c";
    public static final String TELA_MODO_VOLTAR = "v";
    
    private PedidoFachada pedidoFachada;
    
    public String modoTela = "";
    public Pedido pedido = new Pedido();
    

    /**
     * Creates new form CadastrarFuncionario
     * @param pCliente
     */
    public CadastrarPedido(String tipoTela, Pedido pPedido) {
        initComponents();
        
        modoTela = TELA_MODO_EDITAR;
        
        if(tipoTela.equals(TELA_MODO_CADASTRAR)){
            lbl_Status.setVisible(true); 
            txt_Status.setVisible(true);
            modoTela = TELA_MODO_CADASTRAR;
        }
        else{
            
            pedido = pPedido;
            lbl_tela.setText("Editar pedido");
            txt_Status.setText(Uteis.toString(pPedido.getStatusDoPedido()));
            txt_Status.setEnabled(true);
            
            txt_Status.setText(pedido.getStatusDoPedido());
            txt_IdProduto.setText(Uteis.toString(pedido.getProduto().getIdProduto()));
            txt_Qtd_Produto.setText((Uteis.toString(pedido.getQtdProduto())));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_Status = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbl_tela = new javax.swing.JLabel();
        lbl_Status = new javax.swing.JLabel();
        btn_voltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbl_Func1 = new javax.swing.JLabel();
        lbl_nomeProduto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_IdProduto = new javax.swing.JTextField();
        lbl_Func2 = new javax.swing.JLabel();
        lbl_QtdProduto = new javax.swing.JLabel();
        txt_Qtd_Produto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 51, 0));
        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(240, 181, 94));

        lbl_tela.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_tela.setForeground(new java.awt.Color(102, 51, 0));
        lbl_tela.setText("Cadastro de Clientes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_tela)
                .addGap(185, 185, 185))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(lbl_tela)
                .addGap(22, 22, 22))
        );

        lbl_Status.setBackground(new java.awt.Color(240, 181, 94));
        lbl_Status.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Status.setForeground(new java.awt.Color(102, 51, 0));
        lbl_Status.setText("Status Do Pedido");

        btn_voltar.setBackground(new java.awt.Color(255, 255, 255));
        btn_voltar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_voltar.setForeground(new java.awt.Color(102, 51, 0));
        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        jLabel2.setText("*");

        lbl_Func1.setBackground(new java.awt.Color(240, 181, 94));
        lbl_Func1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Func1.setForeground(new java.awt.Color(102, 51, 0));
        lbl_Func1.setText("Id do Produto");

        lbl_nomeProduto.setBackground(new java.awt.Color(240, 181, 94));
        lbl_nomeProduto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_nomeProduto.setForeground(new java.awt.Color(102, 51, 0));
        lbl_nomeProduto.setText("ID Produto");

        jLabel3.setText("*");

        lbl_Func2.setBackground(new java.awt.Color(240, 181, 94));
        lbl_Func2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_Func2.setForeground(new java.awt.Color(102, 51, 0));
        lbl_Func2.setText("CAMPOS COM (*) SÃO OBRIGATORIOS");

        lbl_QtdProduto.setBackground(new java.awt.Color(240, 181, 94));
        lbl_QtdProduto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_QtdProduto.setForeground(new java.awt.Color(102, 51, 0));
        lbl_QtdProduto.setText("Qtd Produto");

        jLabel4.setText("*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbl_QtdProduto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txt_Qtd_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbl_nomeProduto)
                            .addGap(44, 44, 44)
                            .addComponent(jLabel3)
                            .addGap(10, 10, 10)
                            .addComponent(txt_IdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_Func1)
                .addGap(204, 204, 204))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(361, Short.MAX_VALUE)
                    .addComponent(lbl_Func2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(25, 25, 25)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Status)
                    .addComponent(txt_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_Func1)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nomeProduto)
                    .addComponent(txt_IdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_QtdProduto)
                    .addComponent(txt_Qtd_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(133, 133, 133)
                    .addComponent(lbl_Func2)
                    .addContainerGap(229, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        pedidoFachada = new PedidoFachada();

        if ( modoTela.equals(TELA_MODO_CADASTRAR)) {

            pedido.setStatusDoPedido(txt_Status.getText());
            pedido.getProduto().setNomeProduto(txt_IdProduto.getText());
            pedido.setQtdProduto(Integer.parseInt(txt_Qtd_Produto.getText()));
            
            
            try {
                pedidoFachada.salvarPedido(pedido);
                Uteis.AlertInfo(this,"Pedido Cadastrado!!!");
            } catch (Exception ex) {
                Uteis.AlertError(this, ex.getMessage());
            }

        }else if (modoTela.equals(TELA_MODO_EDITAR) ){

            try {
                pedido.setStatusDoPedido(txt_Status.getText());
                pedido.getProduto().setNomeProduto(txt_IdProduto.getText());
                pedido.setQtdProduto(Integer.parseInt(txt_Qtd_Produto.getText()));
                

                pedidoFachada.salvarPedido(pedido);
                Uteis.AlertInfo(this,"Pedido inserido com Sucesso!!!");
            } catch (Exception ex) {
                Uteis.AlertError(this,ex.getMessage());
            }

        }
        
            txt_Status.setText("");
            txt_IdProduto.setText("");
            txt_Qtd_Produto.setText("");
       
      
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed

          ListarPedido Lpedido = new ListarPedido();
          Lpedido.setVisible(true);
          this.setVisible(false);
          Runtime.getRuntime().runFinalization();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {                                  
        // TODO add your handling code here:
        //Listarfuncionario listarLivro = new ListarLivro();
//        listarLivro.setVisible(true);
    }       
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarPedido(CadastrarPedido.TELA_MODO_CADASTRAR, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_voltar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_Func1;
    private javax.swing.JLabel lbl_Func2;
    private javax.swing.JLabel lbl_QtdProduto;
    private javax.swing.JLabel lbl_Status;
    private javax.swing.JLabel lbl_nomeProduto;
    private javax.swing.JLabel lbl_tela;
    private javax.swing.JTextField txt_IdProduto;
    private javax.swing.JTextField txt_Qtd_Produto;
    private javax.swing.JTextField txt_Status;
    // End of variables declaration//GEN-END:variables
}
