/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package burgueriarafael.tela;

/**
 *
 * @author BrunoTiCaVini
 */
public class MenuBurgueria extends javax.swing.JFrame {

    /**
     * Creates new form MenuBurgueria
     */
    public MenuBurgueria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_CadasFuncionario = new javax.swing.JToggleButton();
        btn_CadasCliente = new javax.swing.JToggleButton();
        btn_CadasProduto = new javax.swing.JToggleButton();
        btn_CadastroPedido = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_CadasFuncionario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_CadasFuncionario.setText("Cadastro Funcionario");
        btn_CadasFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CadasFuncionarioActionPerformed(evt);
            }
        });

        btn_CadasCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_CadasCliente.setText("Cadastro Cliente");
        btn_CadasCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CadasClienteActionPerformed(evt);
            }
        });

        btn_CadasProduto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_CadasProduto.setText("Cadastro Produto");
        btn_CadasProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CadasProdutoActionPerformed(evt);
            }
        });

        btn_CadastroPedido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_CadastroPedido.setText("Cadastro Pedido");
        btn_CadastroPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CadastroPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_CadastroPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_CadasCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_CadasFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_CadasProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addComponent(btn_CadastroPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_CadasFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_CadasCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_CadasProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CadasFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CadasFuncionarioActionPerformed

        ListarFuncionario Lfuncionario = new ListarFuncionario();
        Lfuncionario.setVisible(true);
        this.setVisible(false);
        Runtime.getRuntime().runFinalization();

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CadasFuncionarioActionPerformed

    private void btn_CadasClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CadasClienteActionPerformed
      
        ListarCliente Lcliente = new ListarCliente();
        Lcliente.setVisible(true);
        this.setVisible(false);
        Runtime.getRuntime().runFinalization();

// TODO add your handling code here:
    }//GEN-LAST:event_btn_CadasClienteActionPerformed

    private void btn_CadasProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CadasProdutoActionPerformed

        ListarProduto Lproduto = new ListarProduto();
        Lproduto.setVisible(true);
        this.setVisible(false);
        Runtime.getRuntime().runFinalization();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CadasProdutoActionPerformed

    private void btn_CadastroPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CadastroPedidoActionPerformed
  
        ListarPedido Lpedido = new ListarPedido();
        Lpedido.setVisible(true);
        this.setVisible(false);
        Runtime.getRuntime().runFinalization();
             

// TODO add your handling code here:
    }//GEN-LAST:event_btn_CadastroPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuBurgueria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuBurgueria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuBurgueria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuBurgueria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuBurgueria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_CadasCliente;
    private javax.swing.JToggleButton btn_CadasFuncionario;
    private javax.swing.JToggleButton btn_CadasProduto;
    private javax.swing.JToggleButton btn_CadastroPedido;
    // End of variables declaration//GEN-END:variables
}
